---
version: "2.1"
services:
  lavalink:
    image: lyra_lavalink
    container_name: lavalink
    environment:
      - LAVALINK_PWD=LAVALINK_PWD
    ports:
      - ${LAVALINK_PORT}:${LAVALINK_PORT}
    restart: unless-stopped
